### ISSUE TITLE
LAV benchmark

### ISSUE THREAD

**Issue by dvdhfnr** [autonomousvision/carla_garage#22]
Hi! Thanks for your great work!

I would have one question for clarification w.r.t. the "LAV" benchmark. In their original [work](https://github.com/dotchen/LAV) they seem to be using the default [scenario file](https://github.com/carla-simulator/leaderboard/blob/8956c4e0c53bfa24e2bd0ccb1a5269ce47770a57/data/all_towns_traffic_scenarios_public.json) provided by the CARLA Leaderboard 1.0. When interpreting your code/docs correctly, you are using the [scenario file](https://github.com/autonomousvision/transfuser/blob/2022/leaderboard/data/longest6/eval_scenarios.json) from the Transfuser paper, and only the routes from the LAV paper:

> The --scenarios  option should be set to [eval_scenarios.json](https://github.com/autonomousvision/carla_garage/blob/main/leaderboard/data/scenarios/eval_scenarios.json) for both benchmarks.

Is this correct? Are there any reasons for doing so? 

The traffic density seems to be the same as in the original LAV paper:https://github.com/autonomousvision/carla_garage/blob/fb4b180332e465c53095ad6de29429442664882c/leaderboard/leaderboard/scenarios/route_scenario_local.py#L454

Are there any other differences?

**Comment by Kait0** [comment]
I don't think there is a "default" scenario file from the CARLA leaderboard 1.0. The CARLA team released many different scenario files in various branches/repositories (scenario runner / leaderboard) that were also changed over time.
The scenario file used by LAV for evaluation only includes scenarios 1,3 and 4. 
We changed the scenario file to the one used in the TransFuser repository/longest6 because it additionally includes scenarios of the types 7,8,9 and 10.
See also [this discussion](https://github.com/dotchen/LAV/issues/26).

There are no other differences, routes and traffic densities are the same.
