### ISSUE TITLE
Is there an effort to update the code?

### ISSUE THREAD

**Issue by TUMGEKA** [autonomousvision/carla_garage#32]
The code here runs with Ubuntu 18.04, CARLA 0.9.10 and Python 3.6. Are there any current efforts to update the code?

**Comment by Kait0** [comment]
The code runs with python 3.7 and Ubuntu you can also use newer once like 22.04.
We can't upgrade the python version because 3.7 is the newest one that CARLA 0.9.10.1 (the egg/pip library) supports.
The newer CARLA versions like 0.9.15 support up to python 3.8 but are not compatible with the CARLA leaderboard 1.0 code.
Since this repository is supposed to reproduce the experiments in the hidden biases paper we can't upgrade the python or CARLA version.

If you are interested in the CARLA leaderboard 2.0 this code is not so hard to adapt (see [here](https://github.com/autonomousvision/carla_garage/issues/20), although you will need to introduce improvements to get a good score. 
We are working on that but it will likely take a while until we have something that is actually good.
