### ISSUE TITLE
The question about plant

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/carla_garage#34]
I notice that the input route and the output  checkpoint ground truth is same.  How it works?

**Comment by Kait0** [comment]
The checkpoints predict the route centerline, they are the same. Since the route centerline is available in the HD-map there is no reason to predict it, one could also directly use it (e.g.: like in [map_agent](https://github.com/autonomousvision/carla_garage/blob/ce3df9525344133399a3275c1295758164a2fb4b/team_code/map_agent.py#L667C82-L667C100)).
We predict it anyway with the disentangled representation in this plant implementation. There is no particular reason for it. In some sense it makes sure that the architecture has no information bottleneck that prevents it from copying its input.

**Comment by raozhongyu** [comment]
Thanks a lot. I get it.  Have you tried only predict the target speed prediction?

**Comment by Kait0** [comment]
no

**Comment by raozhongyu** [comment]
Hi, I have try to train the model on my own computer, but it seems have a poor results which only can achieve the 60 Ds. I don't find the pretrained models with plant model. Can you provide it?
