### ISSUE TITLE
birdview_map.py issue

### ISSUE THREAD

**Issue by buaazeus** [autonomousvision/carla_garage#37]
Hello, I tried to generate town12.h5 map. When I run birdview_map.py. I got the error below.

Traceback (most recent call last):
  File "./birds_eye_view/birdview_map.py", line 314, in <module>
    dict_masks = MapImage.draw_map_image(world.get_map(), pixels_per_meter)
  File "./birds_eye_view/birdview_map.py", line 42, in draw_map_image
    road_surface = pygame.Surface((width_in_pixels, width_in_pixels))
pygame.error: Out of memory

Carla version is 0.9.15.

Do you know how to resolve this issue?
Thank you.

**Comment by Kait0** [comment]
From what I know the problem is that pygame can not create very large surfaces.
The workaround people use is to reduce the Pixels per Meter parameter to 2ppm.
I am not sure if a proper solution exists, perhaps you need to use another library for rendering.

Also you might need to upgrade the pygame version.
